let architectureItems: [ArchitectureItem] = [
  ArchitectureItem(
    title: "Origami",
    imageNames: ["Gambar1", "Gambar1a", "Gambar1b", "Gambar1c"],
    description: """
Symbolizing the distribution of an overflowing form of creativity, this architectural concept captures the essence of unity through diversity. The structure takes inspiration from the art of origami—an intricate, deliberate folding of geometric planes into a cohesive form—mirroring the idea of bringing together various elements to create a harmonious whole. Much like the diverse textures and patterns found in origami paper, the building aspires to serve as a vessel for social interaction, welcoming people from different backgrounds and fostering a strong sense of belonging. Through this metaphorical and spatial gesture, the architecture becomes more than just a functional space; it becomes a medium for storytelling, collaboration, and community-building, where form and purpose intersect.

The building’s design process began with a direct response to the site’s trapezoidal geometry, using it as a foundation for further formal exploration. From this starting point, the structure evolved through a series of intentional design decisions grounded in spatial efficiency and a forward-looking aesthetic. Employing a subtractive transformation technique, the massing was carved and sculpted to respond to both functional requirements and visual dynamics. The combination of two primary geometric shapes—trapezoid and triangle—serves as the formal language that defines the building’s identity. This geometric interplay not only enhances the structure's visual rhythm but also reinforces its futuristic ambition, creating dynamic angles, dramatic silhouettes, and functional volumes that optimize interior circulation, light penetration, and user experience. The result is an architecture that is simultaneously sculptural and purposeful, a modern emblem of expressive yet thoughtful design.
"""
  ),
  ArchitectureItem(
    title: "The Paradox",
    imageNames: ["Gambar2", "Gambar2a", "Gambar2b", "Gambar2c", "Gambar2d", "Gambar2e", "Gambar2f"],
    description: """
The concept embraces the idea of a paradox itself, something that appears contradictory yet holds underlying truth—reflected in the building's unique form that starkly contrasts with its surroundings. Emphasizing a green modern theme with a mixed-use function, the design integrates residential, recreational, and communal spaces to cater to diverse needs. The building’s radial, contoured form not only challenges conventional shapes but also strategically addresses environmental concerns such as solar heat and airflow optimization. Its design cleverly maximizes natural ventilation and light while maintaining aesthetic appeal and comfort. This architectural decision aligns well with the target demographic, which includes young families, upwardly mobile professionals, and investors looking for long-term value.

Tailored to its audience, the building offers a dynamic living experience. For children in their exploratory years, the curved layout provides various nooks and corners that spark curiosity and interaction. For adults, especially working parents, the apartment includes leisure facilities such as a spa, sauna, gym, and swimming pool to support relaxation and wellness. A central garden serves as a tranquil visual anchor, offering lake views and an island-themed landscape, while the parking area incorporates vertical greenery to reduce heat and glare. Technologically, the residence features smart systems for security, lighting, and appliances, alongside automatic frosted glass on windows and doors to preserve privacy without compromising natural light. Additionally, a sustainable water management system captures and recycles rainwater, reinforcing the building's commitment to energy efficiency and environmental responsibility.
"""
  ),
  ArchitectureItem(
    title: "Sagara",
    imageNames: ["Gambar3", "Gambar3a", "Gambar3b", "Gambar3c", "Gambar3d", "Gambar3e", "Gambar3f", "Gambar3g"],
    description: """
Sagara Convention & Exhibition Center is one of Surabaya’s largest and most iconic venues for exhibitions and conventions, drawing inspiration from the Sanskrit word Sagara, meaning ocean. More than a name, the ocean theme embodies the spirit of Surabaya as a historic port city and symbolizes depth, freedom, exploration, and interconnectedness. The building’s design reflects these qualities through its fluid, wave-like form and its purpose as a dynamic public space. It creates an environment where visitors can explore, connect, and engage in cultural and recreational experiences. The layout encourages movement and discovery, mimicking the vast and unpredictable nature of the sea, while fostering a sense of community and openness.

Architecturally, Sagara merges two key concepts—water and industry—into an organic structure with a modern industrial aesthetic. Its undulating shape allows for strategic leveling, enabling natural light and ventilation to enter the building from various directions, enhancing both comfort and sustainability. The structure is supported by three massive parametric domes, each one meter thick, that form the backbone of the building. These are complemented by adaptive walls that follow the building’s curved geometry. Low-emissivity (low-E) glass on the east and west façades controls heat and sunlight, reducing energy use. With a four-story layout and a 17 x 17 meter structural grid, the building efficiently distributes loads through 1 m² columns—while the top floor, free of interior columns, relies entirely on the strength of the parametric shell. Sagara successfully fuses symbolic meaning with technical innovation, establishing itself as both a cultural landmark and a sustainable architectural achievement.
"""
  ),
  ArchitectureItem(
    title: "Ungaran Harmony Garden",
    imageNames: ["Gambar4", "Gambar4a", "Gambar4b", "Gambar4c", "Gambar4d", "Gambar4e", "Gambar4f", "Gambar4g", "Gambar4h"],
    description: """
Ungaran Harmony Garden is a distinctive agrotourism destination that seamlessly blends natural beauty, local wisdom, and environmental consciousness. Nestled on the slopes of Mount Ungaran, the site offers an immersive experience centered around durian cultivation and processing through an interactive museum and a restaurant overlooking verdant orchards. The architectural approach embraces the land’s natural contours and utilizes eco-friendly materials, allowing the structures to harmonize with their surroundings. More than just a tourist attraction, Ungaran Harmony Garden serves as a model for sustainable development and environmental awareness, promoting a deepened appreciation for agriculture, nature, and culture. The zoning strategy, guided by permaculture principles, organizes the sloped terrain into vertical zones based on function and activity, creating a coherent spatial hierarchy. Drawing on Gordon Cullen’s “Here and There” concept, the site is articulated into foreground, middle ground, and background, producing a layered visual and spatial experience.

Visitors are welcomed through the foreground, which houses high-functionality zones such as the drop-off area, lobby, and dining spaces. The middle ground is more immersive, featuring farmland, walkways, and supporting structures, offering guests hands-on interaction with the agricultural landscape. The background—consisting of lush green scenery—provides a calming visual backdrop that enhances the overall visitor experience. Spatially, the design is influenced by Francis D.K. Ching’s theory of Interlocking Space, fostering strong spatial relationships where each area complements the next. A spiral path configuration guides visitors through the site in a gradual, explorative manner, encouraging continuous discovery. Key circulation elements, such as the inviting entrance and semi-outdoor dining area, enhance cross-ventilation while reducing reliance on artificial lighting and cooling. The architectural form uses clean geometric lines for a modern, timeless aesthetic, while natural materials and recycled components align with permaculture ethics. Integrated vegetation not only cools the environment but also educates visitors on horticultural practices—making the garden both an inspiring retreat and a platform for environmental education and sustainable business.
"""
  ),
  ArchitectureItem(
    title: "B56 Residence",
    imageNames: ["Gambar5", "Gambar5a", "Gambar5b", "Gambar5c", "Gambar5d", "Gambar5e"],
    description: """
The interior concept of B56 Residence is rooted in a tropical modern design approach that prioritizes natural comfort, spatial fluidity, and a strong connection to the surrounding environment. The house is meticulously crafted to respond to the local climate, with a key emphasis on optimizing air circulation and natural lighting throughout the interior. This is achieved through the thoughtful implementation of cross ventilation strategies, where large operable openings are placed on opposite sides of each room to create a continuous flow of fresh air. These openings not only support passive cooling by channeling prevailing breezes but also reduce humidity levels and improve overall indoor air quality. The result is a living space that feels fresh, open, and adaptable to changing weather conditions, enhancing both energy efficiency and daily comfort without the need for excessive mechanical ventilation.

In addition to airflow, the design further embraces nature by integrating vegetation as a central element of the spatial composition. Greenery is not merely decorative but functions as an active architectural component—planted areas are strategically located near windows, along transitional corridors, and within semi-outdoor zones to provide shade, filter sunlight, and lower ambient temperatures. These natural features work in tandem with the home's breathable layout, promoting a sense of calm and well-being throughout the interior. Earth-toned finishes, organic textures, and a minimalist material palette underscore the home's tranquil ambiance, while large glass panels and open-plan arrangements create seamless connections between indoor and outdoor spaces. Altogether, B56 Residence is a refined example of climate-responsive design, where form, function, and nature are carefully balanced to produce a serene, livable, and sustainable home.
"""
  )
]
